// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwDt9iKIn2xhCmhnVntXx-V_TJ7reJ5bo',
    appId: '1:536209386824:ios:be92c648aea8311631577d',
    messagingSenderId: '536209386824',
    projectId: 'text-genie-app',
    storageBucket: 'text-genie-app.appspot.com',
    iosClientId:
        '536209386824-vi1m1vp6277sfae2j0udrhndim3gmkl8.apps.googleusercontent.com',
    iosBundleId: 'com.joseph.textgenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwDt9iKIn2xhCmhnVntXx-V_TJ7reJ5bo',
    appId: '1:536209386824:ios:be92c648aea8311631577d',
    messagingSenderId: '536209386824',
    projectId: 'text-genie-app',
    storageBucket: 'text-genie-app.appspot.com',
    iosClientId:
        '536209386824-vi1m1vp6277sfae2j0udrhndim3gmkl8.apps.googleusercontent.com',
    iosBundleId: 'com.joseph.textgenie',
  );
}
